### PR TITLE
change locale tag format to hyphen notation

### PR DESCRIPTION
**Pull request by benpptung**

### CODE REVIEW

**Comment by smhg** [comment]
@benpptung You can see in the Travis results above/below 1 test is still failing.

**Comment by smhg** [comment]
Yes, it is definitely a breaking change and it will be a new major release. But it is ok if it improves things.

**Comment by benpptung** [comment]
@smhg I'm sorry I am still using Node.js 4 😢, so I cannot run `npm test` in my working environment to know if they pass or not. For your information, I've edited the test script to expect hyphen notation. Also, `trimLocale` and `isLanguageOrLocale` are edited to expect hyphen too. Hope it helps.

**Comment by smhg** [comment]
@benpptung thank you for your work! I'm sorry it took some time to review.

It's almost good to go. Could you please:

- Rebase on origin/master (because of some recent changes).
- Add 1 test where there's a locale in a cookie with the underscore format. That test will fail if I look at your changes. We need an underscore to hyphen conversion to happen so the transition is smooth. I guess it should happen right after `trimLocale` is called in `src/index.js`.

After that, we're good to go and I will immediately release 2.0.

**Comment by smhg** [comment]
@benpptung I've gone ahead and merged this into master.
Apparently input (e.g. from cookie) in underscore format was already handled correctly.

Thanks for your work!

**Pull request closed without merging**
