### PR TITLE
make it work with express 4

### PR DESCRIPTION
**Pull request by stutrek**
doesn't break express 3

### CODE REVIEW

**Comment by smhg** [comment]
Thanks! We'll need to find a way to run tests on both versions of express before releasing a new version to `npm`.
Feel free to send a PR for that too if you'd like.

**Comment by stutrek** [comment]
we could make mock requests from 3 and 4

**Comment by smhg** [comment]
I've added **express3** to `devDependencies` to test on 3 and 4. That's a bit of a hack, but at least it allows for easy version changes (for now).
Mocks aren't a perfect fit to catch changes like `acceptsLanguages` and `hostname` I think.

**Comment by stutrek** [comment]
That's awesome. I didn't know someone had done that.

I like the new style you've been working with, arrow functions and let are awesome. Are you planning on building a dist file to deal with the es6 modules?

**Comment by stutrek** [comment]
I'd like to say one more thing in defense of mocks, then I'll end it forever.

We can rely on express being functional and consistent, their test suite does that. This library only needs to test the functionality of this library. Making mock requests removes a lot of moving parts and the need for port 4000 to be unused while running the tests.

**Comment by smhg** [comment]
Yes, absolutely. The build-script's result will be published to npm.

You're also 100% right about the mocks. I've looked at [node-mocks-http](https://github.com/howardabrams/node-mocks-http) but wasn't convinced it supports different Express versions.
You would just create them manually?

**Comment by stutrek** [comment]
I think if there are any more changes it'll be worth it, but you've already knocked out some great tests.

The node mock looks awesome. You might be able to take a lower tech approach and just make an object that has the properties you're testing.

**Comment by smhg** [comment]
I really agree we should look in that direction, but I can't see how that makes testing Express 5 (or, more likely) minor 4 versions easy.
I want easy tests ;) Also because I don't know much about Express' internals and changes. Monitoring those sounds troublesome.
Let's look at how some of the most popular middlewares solve this and copy that. Any suggestions?

**Comment by stutrek** [comment]
You raise a very good point. The server is a much better, safer idea.

**Pull request merged**
